kind: pipeline
type: docker
name: publish

platform:
  os: linux
  arch: arm64

trigger:
  branch:
    - master

steps:
  - name: build
    image: plugins/docker
    settings:
      repo: cluster.gov:5000/sheepobot
      mirror: http://piracy.gov:5001
      tags:
        - latest
      registry: cluster.gov:5000
      insecure: true
